"""cria tabela log_entry

Revision ID: 2038d9d08857
Revises: db45e61f899e
Create Date: 2026-09-17 18:55:54.238005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2038d9d08857'
down_revision = 'db45e61f899e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('logger_nome', sa.String(length=120), nullable=False),
    sa.Column('mensagem', sa.LargeBinary(), nullable=False),
    sa.Column('mensagem_comprimida', sa.Boolean(), nullable=False),
    sa.Column('contexto', sa.LargeBinary(), nullable=True),
    sa.Column('contexto_comprimida', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entry_criado_em'), 'log_entry', ['criado_em'], unique=False)
    op.create_index(op.f('ix_log_entry_nivel'), 'log_entry', ['nivel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entry_nivel'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_criado_em'), table_name='log_entry')
    op.drop_table('log_entry')
    # ### end Alembic commands ###
