"""cria tabelas produto, mesa e comanda

Revision ID: 8e48319ea484
Revises: 3e2b14f5967a
Create Date: 2026-09-17 18:27:06.172660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e48319ea484'
down_revision = '3e2b14f5967a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesa_numero'), 'mesa', ['numero'], unique=True)
    op.create_table('produto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comanda',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mesa_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('aberta', 'fechada', name='comanda_status'), nullable=False),
    sa.Column('aberta_por', sa.Enum('cliente_qr', 'cliente_manual', 'garcom', name='origem_abertura'), nullable=False),
    sa.Column('aberta_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fechada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comanda_mesa_id'), 'comanda', ['mesa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comanda_mesa_id'), table_name='comanda')
    op.drop_table('comanda')
    op.drop_table('produto')
    op.drop_index(op.f('ix_mesa_numero'), table_name='mesa')
    op.drop_table('mesa')
    # ### end Alembic commands ###
