"""cria tabelas pedido e pedido_item

Revision ID: db45e61f899e
Revises: 8e48319ea484
Create Date: 2026-09-17 18:33:32.433470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db45e61f899e'
down_revision = '8e48319ea484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comanda_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('recebido', 'em_preparo', 'pronto', 'entregue', 'cancelado', name='pedido_status'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comanda_id'], ['comanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_comanda_id'), 'pedido', ['comanda_id'], unique=False)
    op.create_table('pedido_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_item_pedido_id'), 'pedido_item', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_item_pedido_id'), table_name='pedido_item')
    op.drop_table('pedido_item')
    op.drop_index(op.f('ix_pedido_comanda_id'), table_name='pedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###
